name: deep-code
channels:
  - conda-forge
dependencies:
  # Required
  - python >=3.10
  - click
  - fsspec
  - jsonschema
  - requests
  - pandas
  - pystac
  - pyyaml
  - xcube
  # test dependencies
  - numpy
  - pytest
  - pytest-cov