name: deep-code
channels:
  - conda-forge
dependencies:
  # Required
  - python >=3.9
  - click
  - fsspec
  - jsonschema
  - requests
  - pandas
  - pystac
  - pyyaml
  - xcube
  # test dependencies
  - pytest
  - pytest-cov
  - numpy