name: deep-code
channels:
  - conda-forge
dependencies:
  # Required
  - python >=3.10
  - click
  - fsspec
  - jsonschema
  - jsonpickle
  - requests
  - pandas
  - pystac
  - pyyaml
  - xcube
  - xrlint
  - zarr >=2.11,<3
  # test dependencies
  - numpy
  - pytest
  - pytest-cov