name: Unittest deep-code

on:
  push:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout deep-code
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Install deep-code in editable mode
        run: |
          cd /home/runner/work/deep-code/deep-code
          pip install -e .

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          cd /home/runner/work/deep-code/deep-code
          pytest --cov=deep_code --cov-report=xml
